# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=16)),
                ('h_age', models.IntegerField(default=1)),
            ],
        ),
    ]
